// 주일 점심 식사 테이블 명단 (2026-09-06). 원본: scripts/lunch-groups/data.mjs (gitignore).
// ⚠️ 성도 실명 — 사용자 결정(2026-09-06)으로 임시 커밋. 점심 식사 후 이 파일과 관련 분기를 제거할 것.
import type { LunchGroup } from "./lunch-groups.ts";

export const LUNCH_GROUPS: LunchGroup[] = [
  {
    table: 1,
    people: [
      { ko: "정의정", en: "Euijung Jung" },
      { ko: "김지미", en: "Geemee Santucci" },
      { ko: "한순녀", en: "Soonnyeo Han" },
      { ko: "여윤창", en: "David Lu" },
      { ko: null, en: "Jenny Teo" },
      { ko: "하수잔 전도사", en: "Susan Ha, Minister" },
      { ko: "구본윤", en: "Bonyoon Koo" },
      { ko: "박영민", en: "Youngmin Park" },
      { ko: null, en: "Kevin Kim" },
      { ko: "백윤주", en: "Yoonju Yoo" },
    ],
  },
  {
    table: 2,
    people: [
      { ko: "최혁", en: "Hyeok Choe" },
      { ko: "박진섭", en: "Jin Sup Park" },
      { ko: "송석조", en: "Suk Jo Song" },
      { ko: "정해오", en: "Haeoh Jeong" },
      { ko: "유만석", en: "Manseok Yoo" },
      { ko: "박영호", en: "Youngho Park" },
      { ko: "김효진 전도사", en: "Joyce Kim, Minister" },
      { ko: "최은미", en: "Eun Mi Choi" },
      { ko: "오문현", en: "Munhyun Oh" },
      { ko: "홍상후", en: "Sangho Hong" },
    ],
  },
  {
    table: 3,
    people: [
      { ko: "이재훈", en: "Jay Lee" },
      { ko: "양형선", en: "Kenneth Yang" },
      { ko: "오원신", en: "John Oh" },
      { ko: "김운지", en: "Woonji Kim" },
      { ko: "박혜진", en: "Sarah Park" },
      { ko: "김성경", en: "Abbygail Kim" },
      { ko: "배상민", en: "Ethan Bae" },
      { ko: "신에녹", en: "Enoch Shin" },
      { ko: "김동환", en: "Donghwan Kim" },
      { ko: null, en: "Nicholas Lai" },
    ],
  },
  {
    table: 4,
    people: [
      { ko: "이정숙", en: "Rachel Lee" },
      { ko: "박인경", en: "In Kyung Park" },
      { ko: "고성진", en: "Edward Ko" },
      { ko: "이태준", en: "Tyler Lee" },
      { ko: "한상식", en: "Sang Sik Han" },
      { ko: "석연호", en: "Yeun H. Suk" },
      { ko: "김은혁", en: "Elijah Kim" },
      { ko: "김유민", en: "Samuel Kim" },
      { ko: "김요셉", en: "Joseph Kim" },
      { ko: "박윤재", en: "Daniel Pak" },
    ],
  },
  {
    table: 5,
    people: [
      { ko: "박미영", en: "Mi Young Park" },
      { ko: "홍정임", en: "Jamie Yang" },
      { ko: "지은영", en: "Ellie Oh" },
      { ko: "최선영", en: "Sunyoung Choi" },
      { ko: "권혁인", en: "Hyukin Kwon" },
      { ko: "김숙현", en: "Gina Schmitt" },
      { ko: "박윤미", en: "Esther Pak" },
      { ko: "문에바다", en: "Ebada Mun" },
      { ko: "안근영", en: "David Ahn" },
      { ko: "권우송", en: "David Quan" },
    ],
  },
  {
    table: 6,
    people: [
      { ko: "문지옥", en: "Jiok Mun" },
      { ko: "이성미", en: "Sung Mi Lee" },
      { ko: "이경숙", en: "Kyung-sook Lee" },
      { ko: "허재필", en: "Jacob Hur" },
      { ko: "박준영", en: "Joonyoung Park" },
      { ko: "김희선", en: "Hee Sun Kim" },
      { ko: "여승영", en: "Ashley Lu" },
      { ko: "송경한", en: "Kyung Han Song" },
      { ko: "고명도", en: "Philip Ko" },
      { ko: "한세라", en: "Sarah Han" },
    ],
  },
  {
    table: 7,
    people: [
      { ko: "정현이", en: "Hyun Yi Jung" },
      { ko: "이신재", en: "Lois Lee" },
      { ko: "김민경", en: "Minkyong Kim" },
      { ko: null, en: "Sarah Kim" },
      { ko: "오옥환", en: "Okhwan Oh" },
      { ko: "정혜은", en: "Hyeeun Jeong" },
      { ko: "여승준", en: "Daniel Lu" },
      { ko: "허민수", en: "Simeon Hur" },
      { ko: "김안나", en: "Anna Kim" },
      { ko: "김숙미", en: "Sookmi Kim" },
    ],
  },
  {
    table: 8,
    people: [
      { ko: "안정은", en: "Mary Ko" },
      { ko: "박명란", en: "Myungran Park" },
      { ko: "조인상", en: "Insang Cho" },
      { ko: "박정아", en: "Junga Park" },
      { ko: "정미숙", en: "Mi Sook Chung" },
      { ko: "김봉순", en: "Bong Soon Ko" },
      { ko: "양혼용", en: "Hon-yong Yang" },
      { ko: "이기숙", en: "Kisook Lee" },
      { ko: "송순람", en: "Sun Lam Song" },
    ],
  },
  {
    table: 9,
    people: [
      { ko: "한혜은", en: "Rachel Han" },
      { ko: "전동혁", en: "Donghyuk Jun" },
      { ko: "고명수", en: "John Ko" },
      { ko: null, en: "Hephzibah Yoo" },
      { ko: null, en: "Jasmine Yun" },
      { ko: null, en: "Reageine Coone" },
      { ko: null, en: "Daniel Vasquez" },
      { ko: null, en: "Christopher Wong" },
      { ko: "정진남", en: "Daniel Jeong" },
      { ko: null, en: "Wendy Molina" },
    ],
  },
  {
    table: 10,
    people: [
      { ko: "김진선", en: "Joan Kim Suzuki" },
      { ko: "김영은", en: "Youngeun Kim" },
      { ko: "박경선", en: "Kyungsun Park" },
      { ko: "김왕희", en: "Wanghee Kim" },
      { ko: "한호정", en: "Hojung Han" },
      { ko: "정명희", en: "Myunghee Jung" },
      { ko: "김시온", en: "Lily Suzuki" },
      { ko: null, en: "Bob Suprenant" },
      { ko: null, en: "Hang Suprenant" },
    ],
  },
  {
    table: 11,
    people: [
      { ko: "김예준", en: "Yejun Kim" },
      { ko: "김미자", en: "Mija Kim" },
      { ko: "박순영", en: "Soonyoung Park" },
      { ko: "박영숙", en: "Youngsook Han" },
      { ko: "반도균", en: "Dokyun Ban" },
      { ko: null, en: "Edison Malan" },
      { ko: null, en: "Barnabas Ban" },
      { ko: "문기성", en: "Ki Sung Mun" },
      { ko: "김은서", en: "Charlotte Kim" },
      { ko: "정연선", en: "Yeon Sun Kim" },
    ],
  },
  {
    table: 12,
    people: [
      { ko: "김진욱", en: "Jin Wook Kim" },
      { ko: "박수경", en: "Raymond Park" },
      { ko: "정정원 목사", en: "Jungwon Jung, Pastor" },
      { ko: "주경미", en: "Sarah An" },
      { ko: "박종서 목사", en: "Andrew Pak, Pastor" },
      { ko: "문기철 목사", en: "Ki Chul Mun, Pastor" },
      { ko: "조소희", en: "Sohee Cho" },
      { ko: "안재환", en: "Jacob An" },
    ],
  },
  {
    table: 13,
    people: [
      { ko: "김효정", en: "Joanne Pak" },
      { ko: null, en: "Jennifer Shepard" },
      { ko: "김소영", en: "Soyoung Kim" },
      { ko: null, en: "Whitney Shepard" },
      { ko: "문안순", en: "An Soon Moon" },
      { ko: "김숙란", en: "Sukran Jeong" },
      { ko: null, en: "Eunice Ban" },
      { ko: "이인복", en: "In Bok Lee" },
      { ko: "이신일", en: "Shinil Lee" },
    ],
  },
  {
    table: 14,
    people: [
      { ko: "홍우정", en: "Woojeong Hong" },
      { ko: "홍이화", en: "Monica Park" },
      { ko: "나봉례", en: "Bongrye Na" },
      { ko: "양지인", en: "Jiin Yang" },
      { ko: "이주영", en: "Francesca Lee" },
      { ko: null, en: "Haeun Ban" },
      { ko: null, en: "Joanne Chang" },
      { ko: null, en: "Timmy Yoo" },
      { ko: "박선희 선교사", en: "Vicky Park, Missionary" },
    ],
  },
  {
    table: 15,
    people: [
      { ko: null, en: "Marcela Osorio" },
      { ko: null, en: "Sourajit Dey" },
      { ko: null, en: "Dolly Dey" },
      { ko: null, en: "Emmanuel Daring" },
      { ko: null, en: "Leoncio Alberto Balbuca Quizhpe" },
      { ko: null, en: "Jessica Elizabeth Alzamora Benalcazar" },
      { ko: null, en: "Jordan Espinel" },
      { ko: null, en: "Maria Isabel Real" },
      { ko: null, en: "Oscar Osorio" },
      { ko: null, en: "Eric Shepard" },
    ],
  },
  {
    table: 16,
    people: [
      { ko: null, en: "Sandra Osorio, Missionary" },
      { ko: null, en: "Sherline Civil" },
      { ko: null, en: "Gilma Lopez" },
      { ko: null, en: "Diana Osorio" },
      { ko: null, en: "Natalia Osorio" },
      { ko: null, en: "Martha Denis Olaya M." },
      { ko: null, en: "Guillermo Eduardo Cardich G." },
      { ko: null, en: "Jenny Vasquez" },
      { ko: null, en: "Carmen Abreu de Castillo" },
      { ko: null, en: "Lenin Martin Castillo" },
    ],
  },
  {
    table: 17,
    sub: "Moms & Children",
    people: [
      { ko: null, en: "Janet Suk" },
      { ko: "이은진", en: "Eunjin Lee" },
      { ko: "박철홍", en: "Chul Park" },
      { ko: "박이안", en: "Ian Park" },
      { ko: "이수현", en: "Lois Lee" },
      { ko: "이경호", en: "Michael Lee" },
      { ko: "정지현", en: "Angela Lee" },
      { ko: null, en: "Chris Fukuma" },
    ],
  },
  {
    table: 18,
    sub: "Moms & Children",
    people: [
      { ko: "문수영", en: "Suyoung Mun" },
      { ko: "박나언", en: "Natalie Park" },
      { ko: "박선오", en: "Sean Park" },
      { ko: "박예인", en: "Jane Park" },
      { ko: "박테오", en: "Theo Park" },
      { ko: "박홍진", en: "John Park" },
      { ko: "홍수정", en: "Sujung Hong" },
      { ko: "박진도 목사", en: "Joshua Suzuki, Pastor" },
      { ko: null, en: "Danny Oh", tag: "babysitter" },
      { ko: null, en: "Chris Yun", tag: "babysitter" },
    ],
  },
  {
    table: 19,
    sub: "Gideon-20",
    people: [
      { ko: "양태양", en: "Adrian Yang" },
      { ko: "조유니게", en: "Eunice Cho" },
      { ko: null, en: "Nathan Yoo" },
      { ko: null, en: "Ethan Yoo" },
      { ko: "오다니엘", en: "Daniel Oh" },
      { ko: "곽요안나", en: "Joanna Kwak" },
      { ko: "최도일", en: "Doyle Choe" },
      { ko: "허민재", en: "Joel Hur" },
      { ko: null, en: "Charles Civil" },
      { ko: "한율리아", en: "Julia Han" },
    ],
  },
  {
    table: 20,
    sub: "Gideon-20",
    people: [
      { ko: "오노아", en: "Noah Oh" },
      { ko: "박예린", en: "Yerin Park" },
      { ko: "양태미", en: "Kayla Yang" },
      { ko: "김민수", en: "Judah Suzuki" },
      { ko: "양태건", en: "Ian Yang" },
      { ko: "이광현", en: "John Lee" },
      { ko: "이예은", en: "Deborah Lee" },
      { ko: "한백합", en: "Lily Han" },
      { ko: null, en: "Nahum Yoo" },
      { ko: null, en: "Bradley Pluviose" },
    ],
  },
];
